#include "web_bridge.h"

#include <godot_cpp/classes/json.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

#include <emscripten.h>

#include <vector>

// Generated by SConstruct from livekit-client and src/web/bridge.js.
#include "gen/livekit_web_js.gen.h"

using namespace godot;

EM_JS(void, godot_livekit_js_load, (const char *p_source), {
    if (!window.GodotLiveKit) {
        (0, eval)(UTF8ToString(p_source));
    }
});

// Stores the UTF-8 result for godot_livekit_js_take_result and returns its length.
EM_JS(int, godot_livekit_js_call, (const char *p_function, const char *p_args), {
    GodotLiveKit.result = new TextEncoder().encode(GodotLiveKit.call(UTF8ToString(p_function), UTF8ToString(p_args)));
    return GodotLiveKit.result.length;
});

EM_JS(void, godot_livekit_js_take_result, (char *r_buffer), {
    HEAPU8.set(GodotLiveKit.result, r_buffer);
    GodotLiveKit.result = null;
});

static void ensure_loaded() {
    static bool loaded = false;
    if (!loaded) {
        godot_livekit_js_load(reinterpret_cast<const char *>(GODOT_LIVEKIT_WEB_JS));
        loaded = true;
    }
}

Variant godot::web_call(const char *p_function, const Array &p_args) {
    ensure_loaded();
    CharString args = JSON::stringify(p_args).utf8();
    int length = godot_livekit_js_call(p_function, args.get_data());
    std::vector<char> buffer(length);
    godot_livekit_js_take_result(buffer.data());
    Variant result = JSON::parse_string(String::utf8(buffer.data(), length));
    if (result.get_type() == Variant::DICTIONARY && Dictionary(result).has("__error")) {
        UtilityFunctions::push_error("godot-livekit (web): ", Dictionary(result)["__error"]);
        return Variant();
    }
    return result;
}

Dictionary godot::web_call_dict(const char *p_function, const Array &p_args) {
    Variant result = web_call(p_function, p_args);
    return result.get_type() == Variant::DICTIONARY ? Dictionary(result) : Dictionary();
}
